baseURL = "https://DevJie-code.github.io/myblog/"
languageCode = "zh-cn"
title = "麦金塔"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  showReadingTime = true
  showToc = true
  showCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "文章归档"
    url = "/posts/"
    weight = 1
