baseURL = "https://DevJie-code.github.io/myblog/"
languageCode = "zh-cn"
title = "ğŸ” éº¦é‡‘å¡”"
theme = "PaperMod"

[params]
  hideMeta = true
  showDate = false
  enableSearch = true
  disableSpecial1stPost = true
  defaultTheme = "light"
  showReadingTime = false
  showToc = true
  showCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "ğŸ” æœç´¢"
    url = "/search/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 2
  keys = ["title", "permalink", "summary", "content"]

