baseURL = "https://DevJie-code.github.io/myblog/"
languageCode = "zh-cn"
title = "麦金塔"
theme = "PaperMod"

[params]
  enableSearch = true
  disableSpecial1stPost = true
  defaultTheme = "light"
  showReadingTime = true
  showToc = true
  showCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "文章归档"
    url = "/posts/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 2
  keys = ["title", "permalink", "summary", "content"]

  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 2
